### ISSUE TITLE
판매자 도메인 및 회원가입/로그인 구현

### ISSUE THREAD

**Issue by EomYerim** [dnd2dnd/spring-concurrency-issue#6]
### ✨ Describe

판매자 도메인 및 회원가입/로그인 구현
- 회원가입 : 이메일, 비밀번호, 업체명, 업체 주소, 사업자 번호
- 로그인 : 아이디, 비밀번호

### ✅ Tasks

- [x] 판매자 도메인 구현
- [x] 판매자 회원가입 구현
- [x] 판매자 로그인 구현

### 🙋🏻 More
- BaseAuth 추가하여 판매자와 소비자 공통 속성 분리
- 판매자/소비자 회원가입 및 로그인 공통 로직 구현체로 분리
